# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.material_access_data import MaterialAccessData  # noqa: F401,E501
from swagger_server import util


class EntryControlData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, dni: str=None, names_visit: str=None, reason_visit: str=None, area_visit: int=None, person_charge: int=None, type_access: str=None, user: str=None, material_entry: List[MaterialAccessData]=None, observations: str=None, images: List[str]=None):  # noqa: E501
        """EntryControlData - a model defined in Swagger

        :param dni: The dni of this EntryControlData.  # noqa: E501
        :type dni: str
        :param names_visit: The names_visit of this EntryControlData.  # noqa: E501
        :type names_visit: str
        :param reason_visit: The reason_visit of this EntryControlData.  # noqa: E501
        :type reason_visit: str
        :param area_visit: The area_visit of this EntryControlData.  # noqa: E501
        :type area_visit: int
        :param person_charge: The person_charge of this EntryControlData.  # noqa: E501
        :type person_charge: int
        :param type_access: The type_access of this EntryControlData.  # noqa: E501
        :type type_access: str
        :param user: The user of this EntryControlData.  # noqa: E501
        :type user: str
        :param material_entry: The material_entry of this EntryControlData.  # noqa: E501
        :type material_entry: List[MaterialAccessData]
        :param observations: The observations of this EntryControlData.  # noqa: E501
        :type observations: str
        :param images: The images of this EntryControlData.  # noqa: E501
        :type images: List[str]
        """
        self.swagger_types = {
            'dni': str,
            'names_visit': str,
            'reason_visit': str,
            'area_visit': int,
            'person_charge': int,
            'type_access': str,
            'user': str,
            'material_entry': List[MaterialAccessData],
            'observations': str,
            'images': List[str]
        }

        self.attribute_map = {
            'dni': 'dni',
            'names_visit': 'names_visit',
            'reason_visit': 'reason_visit',
            'area_visit': 'area_visit',
            'person_charge': 'person_charge',
            'type_access': 'type_access',
            'user': 'user',
            'material_entry': 'material_entry',
            'observations': 'observations',
            'images': 'images'
        }
        self._dni = dni
        self._names_visit = names_visit
        self._reason_visit = reason_visit
        self._area_visit = area_visit
        self._person_charge = person_charge
        self._type_access = type_access
        self._user = user
        self._material_entry = material_entry
        self._observations = observations
        self._images = images

    @classmethod
    def from_dict(cls, dikt) -> 'EntryControlData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EntryControlData of this EntryControlData.  # noqa: E501
        :rtype: EntryControlData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def dni(self) -> str:
        """Gets the dni of this EntryControlData.


        :return: The dni of this EntryControlData.
        :rtype: str
        """
        return self._dni

    @dni.setter
    def dni(self, dni: str):
        """Sets the dni of this EntryControlData.


        :param dni: The dni of this EntryControlData.
        :type dni: str
        """

        self._dni = dni

    @property
    def names_visit(self) -> str:
        """Gets the names_visit of this EntryControlData.


        :return: The names_visit of this EntryControlData.
        :rtype: str
        """
        return self._names_visit

    @names_visit.setter
    def names_visit(self, names_visit: str):
        """Sets the names_visit of this EntryControlData.


        :param names_visit: The names_visit of this EntryControlData.
        :type names_visit: str
        """

        self._names_visit = names_visit

    @property
    def reason_visit(self) -> str:
        """Gets the reason_visit of this EntryControlData.


        :return: The reason_visit of this EntryControlData.
        :rtype: str
        """
        return self._reason_visit

    @reason_visit.setter
    def reason_visit(self, reason_visit: str):
        """Sets the reason_visit of this EntryControlData.


        :param reason_visit: The reason_visit of this EntryControlData.
        :type reason_visit: str
        """

        self._reason_visit = reason_visit

    @property
    def area_visit(self) -> int:
        """Gets the area_visit of this EntryControlData.


        :return: The area_visit of this EntryControlData.
        :rtype: int
        """
        return self._area_visit

    @area_visit.setter
    def area_visit(self, area_visit: int):
        """Sets the area_visit of this EntryControlData.


        :param area_visit: The area_visit of this EntryControlData.
        :type area_visit: int
        """

        self._area_visit = area_visit

    @property
    def person_charge(self) -> int:
        """Gets the person_charge of this EntryControlData.


        :return: The person_charge of this EntryControlData.
        :rtype: int
        """
        return self._person_charge

    @person_charge.setter
    def person_charge(self, person_charge: int):
        """Sets the person_charge of this EntryControlData.


        :param person_charge: The person_charge of this EntryControlData.
        :type person_charge: int
        """

        self._person_charge = person_charge

    @property
    def type_access(self) -> str:
        """Gets the type_access of this EntryControlData.


        :return: The type_access of this EntryControlData.
        :rtype: str
        """
        return self._type_access

    @type_access.setter
    def type_access(self, type_access: str):
        """Sets the type_access of this EntryControlData.


        :param type_access: The type_access of this EntryControlData.
        :type type_access: str
        """

        self._type_access = type_access

    @property
    def user(self) -> str:
        """Gets the user of this EntryControlData.


        :return: The user of this EntryControlData.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user: str):
        """Sets the user of this EntryControlData.


        :param user: The user of this EntryControlData.
        :type user: str
        """

        self._user = user

    @property
    def material_entry(self) -> List[MaterialAccessData]:
        """Gets the material_entry of this EntryControlData.


        :return: The material_entry of this EntryControlData.
        :rtype: List[MaterialAccessData]
        """
        return self._material_entry

    @material_entry.setter
    def material_entry(self, material_entry: List[MaterialAccessData]):
        """Sets the material_entry of this EntryControlData.


        :param material_entry: The material_entry of this EntryControlData.
        :type material_entry: List[MaterialAccessData]
        """

        self._material_entry = material_entry

    @property
    def observations(self) -> str:
        """Gets the observations of this EntryControlData.


        :return: The observations of this EntryControlData.
        :rtype: str
        """
        return self._observations

    @observations.setter
    def observations(self, observations: str):
        """Sets the observations of this EntryControlData.


        :param observations: The observations of this EntryControlData.
        :type observations: str
        """

        self._observations = observations

    @property
    def images(self) -> List[str]:
        """Gets the images of this EntryControlData.


        :return: The images of this EntryControlData.
        :rtype: List[str]
        """
        return self._images

    @images.setter
    def images(self, images: List[str]):
        """Sets the images of this EntryControlData.


        :param images: The images of this EntryControlData.
        :type images: List[str]
        """

        self._images = images

    @classmethod
    def from_json(cls, data: Dict) -> "EntryControlData":
        obj = cls()

        for attr, json_key in obj.attribute_map.items():
            if json_key in data:
                setattr(obj, attr, data[json_key])

        return obj
