# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ReceptionDetailData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, reception_id: int=None, product_id: int=None, expected_quantity: int=None, received_quantity: int=None, observations: str=None):  # noqa: E501
        """ReceptionDetailData - a model defined in Swagger

        :param reception_id: The reception_id of this ReceptionDetailData.  # noqa: E501
        :type reception_id: int
        :param product_id: The product_id of this ReceptionDetailData.  # noqa: E501
        :type product_id: int
        :param expected_quantity: The expected_quantity of this ReceptionDetailData.  # noqa: E501
        :type expected_quantity: int
        :param received_quantity: The received_quantity of this ReceptionDetailData.  # noqa: E501
        :type received_quantity: int
        :param observations: The observations of this ReceptionDetailData.  # noqa: E501
        :type observations: str
        """
        self.swagger_types = {
            'reception_id': int,
            'product_id': int,
            'expected_quantity': int,
            'received_quantity': int,
            'observations': str
        }

        self.attribute_map = {
            'reception_id': 'reception_id',
            'product_id': 'product_id',
            'expected_quantity': 'expected_quantity',
            'received_quantity': 'received_quantity',
            'observations': 'observations'
        }
        self._reception_id = reception_id
        self._product_id = product_id
        self._expected_quantity = expected_quantity
        self._received_quantity = received_quantity
        self._observations = observations

    @classmethod
    def from_dict(cls, dikt) -> 'ReceptionDetailData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ReceptionDetailData of this ReceptionDetailData.  # noqa: E501
        :rtype: ReceptionDetailData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def reception_id(self) -> int:
        """Gets the reception_id of this ReceptionDetailData.


        :return: The reception_id of this ReceptionDetailData.
        :rtype: int
        """
        return self._reception_id

    @reception_id.setter
    def reception_id(self, reception_id: int):
        """Sets the reception_id of this ReceptionDetailData.


        :param reception_id: The reception_id of this ReceptionDetailData.
        :type reception_id: int
        """

        self._reception_id = reception_id

    @property
    def product_id(self) -> int:
        """Gets the product_id of this ReceptionDetailData.


        :return: The product_id of this ReceptionDetailData.
        :rtype: int
        """
        return self._product_id

    @product_id.setter
    def product_id(self, product_id: int):
        """Sets the product_id of this ReceptionDetailData.


        :param product_id: The product_id of this ReceptionDetailData.
        :type product_id: int
        """

        self._product_id = product_id

    @property
    def expected_quantity(self) -> int:
        """Gets the expected_quantity of this ReceptionDetailData.


        :return: The expected_quantity of this ReceptionDetailData.
        :rtype: int
        """
        return self._expected_quantity

    @expected_quantity.setter
    def expected_quantity(self, expected_quantity: int):
        """Sets the expected_quantity of this ReceptionDetailData.


        :param expected_quantity: The expected_quantity of this ReceptionDetailData.
        :type expected_quantity: int
        """

        self._expected_quantity = expected_quantity

    @property
    def received_quantity(self) -> int:
        """Gets the received_quantity of this ReceptionDetailData.


        :return: The received_quantity of this ReceptionDetailData.
        :rtype: int
        """
        return self._received_quantity

    @received_quantity.setter
    def received_quantity(self, received_quantity: int):
        """Sets the received_quantity of this ReceptionDetailData.


        :param received_quantity: The received_quantity of this ReceptionDetailData.
        :type received_quantity: int
        """

        self._received_quantity = received_quantity

    @property
    def observations(self) -> str:
        """Gets the observations of this ReceptionDetailData.


        :return: The observations of this ReceptionDetailData.
        :rtype: str
        """
        return self._observations

    @observations.setter
    def observations(self, observations: str):
        """Sets the observations of this ReceptionDetailData.


        :param observations: The observations of this ReceptionDetailData.
        :type observations: str
        """

        self._observations = observations
