# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.request_dispatch_dispatch_data_products_sku import RequestDispatchDispatchDataProductsSku  # noqa: F401,E501
from swagger_server import util


class RequestSkuData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, type_sku: str=None, products: List[RequestDispatchDispatchDataProductsSku]=None):  # noqa: E501
        """RequestSkuData - a model defined in Swagger

        :param type_sku: The type_sku of this RequestSkuData.  # noqa: E501
        :type type_sku: str
        :param products: The products of this RequestSkuData.  # noqa: E501
        :type products: List[RequestDispatchDispatchDataProductsSku]
        """
        self.swagger_types = {
            'type_sku': str,
            'products': List[RequestDispatchDispatchDataProductsSku]
        }

        self.attribute_map = {
            'type_sku': 'type_sku',
            'products': 'products'
        }
        self._type_sku = type_sku
        self._products = products

    @classmethod
    def from_dict(cls, dikt) -> 'RequestSkuData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestSkuData of this RequestSkuData.  # noqa: E501
        :rtype: RequestSkuData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type_sku(self) -> str:
        """Gets the type_sku of this RequestSkuData.


        :return: The type_sku of this RequestSkuData.
        :rtype: str
        """
        return self._type_sku

    @type_sku.setter
    def type_sku(self, type_sku: str):
        """Sets the type_sku of this RequestSkuData.


        :param type_sku: The type_sku of this RequestSkuData.
        :type type_sku: str
        """

        self._type_sku = type_sku

    @property
    def products(self) -> List[RequestDispatchDispatchDataProductsSku]:
        """Gets the products of this RequestSkuData.


        :return: The products of this RequestSkuData.
        :rtype: List[RequestDispatchDispatchDataProductsSku]
        """
        return self._products

    @products.setter
    def products(self, products: List[RequestDispatchDispatchDataProductsSku]):
        """Sets the products of this RequestSkuData.


        :param products: The products of this RequestSkuData.
        :type products: List[RequestDispatchDispatchDataProductsSku]
        """

        self._products = products
