# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RequestDispatchDispatchDataProductsSku(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id_product: int=None, quantiy: float=None):  # noqa: E501
        """RequestDispatchDispatchDataProductsSku - a model defined in Swagger

        :param id_product: The id_product of this RequestDispatchDispatchDataProductsSku.  # noqa: E501
        :type id_product: int
        :param quantiy: The quantiy of this RequestDispatchDispatchDataProductsSku.  # noqa: E501
        :type quantiy: float
        """
        self.swagger_types = {
            'id_product': int,
            'quantiy': float
        }

        self.attribute_map = {
            'id_product': 'id_product',
            'quantiy': 'quantiy'
        }
        self._id_product = id_product
        self._quantiy = quantiy

    @classmethod
    def from_dict(cls, dikt) -> 'RequestDispatchDispatchDataProductsSku':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestDispatch_dispatch_data_products_sku of this RequestDispatchDispatchDataProductsSku.  # noqa: E501
        :rtype: RequestDispatchDispatchDataProductsSku
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_product(self) -> int:
        """Gets the id_product of this RequestDispatchDispatchDataProductsSku.


        :return: The id_product of this RequestDispatchDispatchDataProductsSku.
        :rtype: int
        """
        return self._id_product

    @id_product.setter
    def id_product(self, id_product: int):
        """Sets the id_product of this RequestDispatchDispatchDataProductsSku.


        :param id_product: The id_product of this RequestDispatchDispatchDataProductsSku.
        :type id_product: int
        """

        self._id_product = id_product

    @property
    def quantiy(self) -> float:
        """Gets the quantiy of this RequestDispatchDispatchDataProductsSku.


        :return: The quantiy of this RequestDispatchDispatchDataProductsSku.
        :rtype: float
        """
        return self._quantiy

    @quantiy.setter
    def quantiy(self, quantiy: float):
        """Sets the quantiy of this RequestDispatchDispatchDataProductsSku.


        :param quantiy: The quantiy of this RequestDispatchDispatchDataProductsSku.
        :type quantiy: float
        """

        self._quantiy = quantiy
