# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.entry_control_data import EntryControlData  # noqa: F401,E501
from swagger_server import util


class RequestEntryControl(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, entry_data: EntryControlData=None, channel: str=None, external_transaction_id: str=None):  # noqa: E501
        """RequestEntryControl - a model defined in Swagger

        :param entry_data: The entry_data of this RequestEntryControl.  # noqa: E501
        :type entry_data: EntryControlData
        :param channel: The channel of this RequestEntryControl.  # noqa: E501
        :type channel: str
        :param external_transaction_id: The external_transaction_id of this RequestEntryControl.  # noqa: E501
        :type external_transaction_id: str
        """
        self.swagger_types = {
            'entry_data': EntryControlData,
            'channel': str,
            'external_transaction_id': str
        }

        self.attribute_map = {
            'entry_data': 'entry_data',
            'channel': 'channel',
            'external_transaction_id': 'externalTransactionId'
        }
        self._entry_data = entry_data
        self._channel = channel
        self._external_transaction_id = external_transaction_id

    @classmethod
    def from_dict(cls, dikt) -> 'RequestEntryControl':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestEntryControl of this RequestEntryControl.  # noqa: E501
        :rtype: RequestEntryControl
        """
        return util.deserialize_model(dikt, cls)

    @property
    def entry_data(self) -> EntryControlData:
        """Gets the entry_data of this RequestEntryControl.


        :return: The entry_data of this RequestEntryControl.
        :rtype: EntryControlData
        """
        return self._entry_data

    @entry_data.setter
    def entry_data(self, entry_data: EntryControlData):
        """Sets the entry_data of this RequestEntryControl.


        :param entry_data: The entry_data of this RequestEntryControl.
        :type entry_data: EntryControlData
        """

        self._entry_data = entry_data

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestEntryControl.


        :return: The channel of this RequestEntryControl.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestEntryControl.


        :param channel: The channel of this RequestEntryControl.
        :type channel: str
        """

        self._channel = channel

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this RequestEntryControl.


        :return: The external_transaction_id of this RequestEntryControl.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this RequestEntryControl.


        :param external_transaction_id: The external_transaction_id of this RequestEntryControl.
        :type external_transaction_id: str
        """

        self._external_transaction_id = external_transaction_id
