# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.request_sku_data import RequestSkuData  # noqa: F401,E501
from swagger_server import util


class RequestDispatchDispatchData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, weight: float=None, vehicle_type: int=None, destiny: int=None, status_id: int=None, order_number: str=None, truck_license: str=None, user: str=None, driver: str=None, images: List[str]=None, sku: List[RequestSkuData]=None, observations: str=None):  # noqa: E501
        """RequestDispatchDispatchData - a model defined in Swagger

        :param weight: The weight of this RequestDispatchDispatchData.  # noqa: E501
        :type weight: float
        :param vehicle_type: The vehicle_type of this RequestDispatchDispatchData.  # noqa: E501
        :type vehicle_type: int
        :param destiny: The destiny of this RequestDispatchDispatchData.  # noqa: E501
        :type destiny: int
        :param status_id: The status_id of this RequestDispatchDispatchData.  # noqa: E501
        :type status_id: int
        :param order_number: The order_number of this RequestDispatchDispatchData.  # noqa: E501
        :type order_number: str
        :param truck_license: The truck_license of this RequestDispatchDispatchData.  # noqa: E501
        :type truck_license: str
        :param user: The user of this RequestDispatchDispatchData.  # noqa: E501
        :type user: str
        :param driver: The driver of this RequestDispatchDispatchData.  # noqa: E501
        :type driver: str
        :param images: The images of this RequestDispatchDispatchData.  # noqa: E501
        :type images: List[str]
        :param sku: The sku of this RequestDispatchDispatchData.  # noqa: E501
        :type sku: List[RequestSkuData]
        :param observations: The observations of this RequestDispatchDispatchData.  # noqa: E501
        :type observations: str
        """
        self.swagger_types = {
            'weight': float,
            'vehicle_type': int,
            'destiny': int,
            'status_id': int,
            'order_number': str,
            'truck_license': str,
            'user': str,
            'driver': str,
            'images': List[str],
            'sku': List[RequestSkuData],
            'observations': str
        }

        self.attribute_map = {
            'weight': 'weight',
            'vehicle_type': 'vehicle_type',
            'destiny': 'destiny',
            'status_id': 'status_id',
            'order_number': 'order_number',
            'truck_license': 'truck_license',
            'user': 'user',
            'driver': 'driver',
            'images': 'images',
            'sku': 'sku',
            'observations': 'observations'
        }
        self._weight = weight
        self._vehicle_type = vehicle_type
        self._destiny = destiny
        self._status_id = status_id
        self._order_number = order_number
        self._truck_license = truck_license
        self._user = user
        self._driver = driver
        self._images = images
        self._sku = sku
        self._observations = observations

    @classmethod
    def from_dict(cls, dikt) -> 'RequestDispatchDispatchData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestDispatch_dispatch_data of this RequestDispatchDispatchData.  # noqa: E501
        :rtype: RequestDispatchDispatchData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def weight(self) -> float:
        """Gets the weight of this RequestDispatchDispatchData.


        :return: The weight of this RequestDispatchDispatchData.
        :rtype: float
        """
        return self._weight

    @weight.setter
    def weight(self, weight: float):
        """Sets the weight of this RequestDispatchDispatchData.


        :param weight: The weight of this RequestDispatchDispatchData.
        :type weight: float
        """

        self._weight = weight

    @property
    def vehicle_type(self) -> int:
        """Gets the vehicle_type of this RequestDispatchDispatchData.


        :return: The vehicle_type of this RequestDispatchDispatchData.
        :rtype: int
        """
        return self._vehicle_type

    @vehicle_type.setter
    def vehicle_type(self, vehicle_type: int):
        """Sets the vehicle_type of this RequestDispatchDispatchData.


        :param vehicle_type: The vehicle_type of this RequestDispatchDispatchData.
        :type vehicle_type: int
        """

        self._vehicle_type = vehicle_type

    @property
    def destiny(self) -> int:
        """Gets the destiny of this RequestDispatchDispatchData.


        :return: The destiny of this RequestDispatchDispatchData.
        :rtype: int
        """
        return self._destiny

    @destiny.setter
    def destiny(self, destiny: int):
        """Sets the destiny of this RequestDispatchDispatchData.


        :param destiny: The destiny of this RequestDispatchDispatchData.
        :type destiny: int
        """

        self._destiny = destiny

    @property
    def status_id(self) -> int:
        """Gets the status_id of this RequestDispatchDispatchData.


        :return: The status_id of this RequestDispatchDispatchData.
        :rtype: int
        """
        return self._status_id

    @status_id.setter
    def status_id(self, status_id: int):
        """Sets the status_id of this RequestDispatchDispatchData.


        :param status_id: The status_id of this RequestDispatchDispatchData.
        :type status_id: int
        """

        self._status_id = status_id

    @property
    def order_number(self) -> str:
        """Gets the order_number of this RequestDispatchDispatchData.


        :return: The order_number of this RequestDispatchDispatchData.
        :rtype: str
        """
        return self._order_number

    @order_number.setter
    def order_number(self, order_number: str):
        """Sets the order_number of this RequestDispatchDispatchData.


        :param order_number: The order_number of this RequestDispatchDispatchData.
        :type order_number: str
        """

        self._order_number = order_number

    @property
    def truck_license(self) -> str:
        """Gets the truck_license of this RequestDispatchDispatchData.


        :return: The truck_license of this RequestDispatchDispatchData.
        :rtype: str
        """
        return self._truck_license

    @truck_license.setter
    def truck_license(self, truck_license: str):
        """Sets the truck_license of this RequestDispatchDispatchData.


        :param truck_license: The truck_license of this RequestDispatchDispatchData.
        :type truck_license: str
        """

        self._truck_license = truck_license

    @property
    def user(self) -> str:
        """Gets the user of this RequestDispatchDispatchData.


        :return: The user of this RequestDispatchDispatchData.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user: str):
        """Sets the user of this RequestDispatchDispatchData.


        :param user: The user of this RequestDispatchDispatchData.
        :type user: str
        """

        self._user = user

    @property
    def driver(self) -> str:
        """Gets the driver of this RequestDispatchDispatchData.


        :return: The driver of this RequestDispatchDispatchData.
        :rtype: str
        """
        return self._driver

    @driver.setter
    def driver(self, driver: str):
        """Sets the driver of this RequestDispatchDispatchData.


        :param driver: The driver of this RequestDispatchDispatchData.
        :type driver: str
        """

        self._driver = driver

    @property
    def images(self) -> List[str]:
        """Gets the images of this RequestDispatchDispatchData.


        :return: The images of this RequestDispatchDispatchData.
        :rtype: List[str]
        """
        return self._images

    @images.setter
    def images(self, images: List[str]):
        """Sets the images of this RequestDispatchDispatchData.


        :param images: The images of this RequestDispatchDispatchData.
        :type images: List[str]
        """

        self._images = images

    @property
    def sku(self) -> List[RequestSkuData]:
        """Gets the sku of this RequestDispatchDispatchData.


        :return: The sku of this RequestDispatchDispatchData.
        :rtype: List[RequestSkuData]
        """
        return self._sku

    @sku.setter
    def sku(self, sku: List[RequestSkuData]):
        """Sets the sku of this RequestDispatchDispatchData.


        :param sku: The sku of this RequestDispatchDispatchData.
        :type sku: List[RequestSkuData]
        """

        self._sku = sku

    @property
    def observations(self) -> str:
        """Gets the observations of this RequestDispatchDispatchData.


        :return: The observations of this RequestDispatchDispatchData.
        :rtype: str
        """
        return self._observations

    @observations.setter
    def observations(self, observations: str):
        """Sets the observations of this RequestDispatchDispatchData.


        :param observations: The observations of this RequestDispatchDispatchData.
        :type observations: str
        """

        self._observations = observations

    @classmethod
    def from_json(cls, data: Dict) -> "RequestDispatchDispatchData":
        obj = cls()

        for attr, json_key in obj.attribute_map.items():
            if json_key in data:
                setattr(obj, attr, data[json_key])

        return obj
