# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RequestDispatchDispatchDataProductsSku(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id_product: int=None, quantity: int=None):  # noqa: E501
        """RequestDispatchDispatchDataProductsSku - a model defined in Swagger

        :param id_product: The id_product of this RequestDispatchDispatchDataProductsSku.  # noqa: E501
        :type id_product: int
        :param quantity: The quantity of this RequestDispatchDispatchDataProductsSku.  # noqa: E501
        :type quantity: int
        """
        self.swagger_types = {
            'id_product': int,
            'quantity': int
        }

        self.attribute_map = {
            'id_product': 'id_product',
            'quantity': 'quantity'
        }
        self._id_product = id_product
        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt) -> 'RequestDispatchDispatchDataProductsSku':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestDispatch_dispatch_data_products_sku of this RequestDispatchDispatchDataProductsSku.  # noqa: E501
        :rtype: RequestDispatchDispatchDataProductsSku
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_product(self) -> int:
        """Gets the id_product of this RequestDispatchDispatchDataProductsSku.


        :return: The id_product of this RequestDispatchDispatchDataProductsSku.
        :rtype: int
        """
        return self._id_product

    @id_product.setter
    def id_product(self, id_product: int):
        """Sets the id_product of this RequestDispatchDispatchDataProductsSku.


        :param id_product: The id_product of this RequestDispatchDispatchDataProductsSku.
        :type id_product: int
        """

        self._id_product = id_product

    @property
    def quantity(self) -> int:
        """Gets the quantity of this RequestDispatchDispatchDataProductsSku.


        :return: The quantity of this RequestDispatchDispatchDataProductsSku.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this RequestDispatchDispatchDataProductsSku.


        :param quantity: The quantity of this RequestDispatchDispatchDataProductsSku.
        :type quantity: int
        """

        self._quantity = quantity
