# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.reception_data import Receptiondata  # noqa: F401,E501
from swagger_server import util


class RequestReception(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, reception_data: Receptiondata=None, channel: str=None, external_transaction_id: str=None):  # noqa: E501
        """RequestReception - a model defined in Swagger

        :param reception_data: The reception_data of this RequestReception.  # noqa: E501
        :type reception_data: Receptiondata
        :param channel: The channel of this RequestReception.  # noqa: E501
        :type channel: str
        :param external_transaction_id: The external_transaction_id of this RequestReception.  # noqa: E501
        :type external_transaction_id: str
        """
        self.swagger_types = {
            'reception_data': Receptiondata,
            'channel': str,
            'external_transaction_id': str
        }

        self.attribute_map = {
            'reception_data': 'reception_data',
            'channel': 'channel',
            'external_transaction_id': 'externalTransactionId'
        }
        self._reception_data = reception_data
        self._channel = channel
        self._external_transaction_id = external_transaction_id

    @classmethod
    def from_dict(cls, dikt) -> 'RequestReception':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestReception of this RequestReception.  # noqa: E501
        :rtype: RequestReception
        """
        return util.deserialize_model(dikt, cls)

    @property
    def reception_data(self) -> Receptiondata:
        """Gets the reception_data of this RequestReception.


        :return: The reception_data of this RequestReception.
        :rtype: Receptiondata
        """
        return self._reception_data

    @reception_data.setter
    def reception_data(self, reception_data: Receptiondata):
        """Sets the reception_data of this RequestReception.


        :param reception_data: The reception_data of this RequestReception.
        :type reception_data: Receptiondata
        """

        self._reception_data = reception_data

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestReception.


        :return: The channel of this RequestReception.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestReception.


        :param channel: The channel of this RequestReception.
        :type channel: str
        """

        self._channel = channel

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this RequestReception.


        :return: The external_transaction_id of this RequestReception.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this RequestReception.


        :param external_transaction_id: The external_transaction_id of this RequestReception.
        :type external_transaction_id: str
        """

        self._external_transaction_id = external_transaction_id
