# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.request_dispatch_dispatch_data import RequestDispatchDispatchData  # noqa: F401,E501
from swagger_server import util


class RequestDispatch(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, dispatch_data: RequestDispatchDispatchData=None, channel: str=None, external_transaction_id: str=None):  # noqa: E501
        """RequestDispatch - a model defined in Swagger

        :param dispatch_data: The dispatch_data of this RequestDispatch.  # noqa: E501
        :type dispatch_data: RequestDispatchDispatchData
        :param channel: The channel of this RequestDispatch.  # noqa: E501
        :type channel: str
        :param external_transaction_id: The external_transaction_id of this RequestDispatch.  # noqa: E501
        :type external_transaction_id: str
        """
        self.swagger_types = {
            'dispatch_data': RequestDispatchDispatchData,
            'channel': str,
            'external_transaction_id': str
        }

        self.attribute_map = {
            'dispatch_data': 'dispatch_data',
            'channel': 'channel',
            'external_transaction_id': 'externalTransactionId'
        }
        self._dispatch_data = dispatch_data
        self._channel = channel
        self._external_transaction_id = external_transaction_id

    @classmethod
    def from_dict(cls, dikt) -> 'RequestDispatch':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestDispatch of this RequestDispatch.  # noqa: E501
        :rtype: RequestDispatch
        """
        return util.deserialize_model(dikt, cls)

    @property
    def dispatch_data(self) -> RequestDispatchDispatchData:
        """Gets the dispatch_data of this RequestDispatch.


        :return: The dispatch_data of this RequestDispatch.
        :rtype: RequestDispatchDispatchData
        """
        return self._dispatch_data

    @dispatch_data.setter
    def dispatch_data(self, dispatch_data: RequestDispatchDispatchData):
        """Sets the dispatch_data of this RequestDispatch.


        :param dispatch_data: The dispatch_data of this RequestDispatch.
        :type dispatch_data: RequestDispatchDispatchData
        """

        self._dispatch_data = dispatch_data

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestDispatch.


        :return: The channel of this RequestDispatch.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestDispatch.


        :param channel: The channel of this RequestDispatch.
        :type channel: str
        """

        self._channel = channel

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this RequestDispatch.


        :return: The external_transaction_id of this RequestDispatch.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this RequestDispatch.


        :param external_transaction_id: The external_transaction_id of this RequestDispatch.
        :type external_transaction_id: str
        """

        self._external_transaction_id = external_transaction_id
